#pragma once

#include "metric_descriptor.hpp"

#include <array>

namespace cw::server
{

inline constexpr std::array<metric_descriptor, metric_count> metric_descriptors{{
    {metric_id::server_initializations, metric_kind::counter,
     "server.initializations", "Number of server initialization attempts"},
    {metric_id::server_initialization_duration, metric_kind::duration,
     "server.initialization.duration", "Duration of server initialization attempts"},
    {metric_id::server_active_projects, metric_kind::gauge,
     "server.active_projects", "Current number of active projects"},
    {metric_id::project_initializations, metric_kind::counter,
     "project.initializations", "Number of project initialization attempts"},
    {metric_id::project_initialization_duration, metric_kind::duration,
     "project.initialization.duration", "Duration of project initialization attempts"},
    {metric_id::project_load_count, metric_kind::counter,
     "project.load.count", "Number of complete project load attempts"},
    {metric_id::project_load_duration, metric_kind::duration,
     "project.load.duration", "Wall duration of complete project load attempts"},
    {metric_id::project_configuration_load_count, metric_kind::counter,
     "project.configuration.load.count", "Number of project configuration load attempts"},
    {metric_id::project_configuration_load_duration, metric_kind::duration,
     "project.configuration.load.duration", "Duration of project configuration load attempts"},
    {metric_id::project_configuration_parse_duration, metric_kind::duration,
     "project.configuration.parse.duration", "Duration of project configuration JSON parsing"},
    {metric_id::project_configuration_path_resolution_duration, metric_kind::duration,
     "project.configuration.path_resolution.duration", "Duration of project item path resolution"},
    {metric_id::project_configuration_item_count, metric_kind::counter,
     "project.configuration.item.count", "Number of successfully loaded project items"},
    {metric_id::project_composition_resolve_count, metric_kind::counter,
     "project.composition.resolve.count", "Number of project composition resolution attempts"},
    {metric_id::project_composition_resolve_duration, metric_kind::duration,
     "project.composition.resolve.duration", "Duration of project composition resolution attempts"},
    {metric_id::project_composition_file_count, metric_kind::counter,
     "project.composition.file.count", "Number of subproject configuration files loaded"},
    {metric_id::project_composition_cache_hit_count, metric_kind::counter,
     "project.composition.cache_hit.count", "Number of deduplicated project composition references"},
    {metric_id::project_composition_max_parallel_workers, metric_kind::gauge,
     "project.composition.max_parallel_workers", "Maximum active project composition workers in the latest resolution"},
    {metric_id::frontend_build_count, metric_kind::counter,
     "frontend.build.count", "Number of frontend generation attempts"},
    {metric_id::frontend_build_duration, metric_kind::duration,
     "frontend.build.duration", "Wall duration of frontend generation attempts"},
    {metric_id::frontend_g0_acquire_prepare_duration, metric_kind::duration,
     "frontend.g0.acquire_prepare.duration", "G0 Source acquisition preparation wall duration"},
    {metric_id::frontend_g0_acquire_execute_duration, metric_kind::duration,
     "frontend.g0.acquire_execute.duration", "G0 parallel Source acquisition execution wall duration"},
    {metric_id::frontend_g0_acquire_apply_duration, metric_kind::duration,
     "frontend.g0.acquire_apply.duration", "G0 Source acquisition apply wall duration"},
    {metric_id::frontend_g0_discovery_duration, metric_kind::duration,
     "frontend.g0.discovery.duration", "G0 discovery and lexical analysis wall duration"},
    {metric_id::frontend_g0_validation_duration, metric_kind::duration,
     "frontend.g0.validation.duration", "G0 frontend dependency validation wall duration"},
    {metric_id::frontend_g0_semantic_duration, metric_kind::duration,
     "frontend.g0.semantic.duration", "G0 parallel parse and semantic capture wall duration"},
    {metric_id::frontend_g0_publish_duration, metric_kind::duration,
     "frontend.g0.publish.duration", "G0 Source publication wall duration"},
    {metric_id::frontend_g0_publish_reserve_scan_duration, metric_kind::duration,
     "frontend.g0.publish.reserve_scan.duration", "G0 publication reserve-hint scan wall duration"},
    {metric_id::frontend_g0_publish_string_reserve_duration, metric_kind::duration,
     "frontend.g0.publish.string_reserve.duration", "G0 String Registry reserve wall duration before publication"},
    {metric_id::frontend_g0_publish_source_replace_duration, metric_kind::duration,
     "frontend.g0.publish.source_replace.duration", "Detailed G0 source replacement opening wall duration"},
    {metric_id::frontend_g0_publish_enum_name_duration, metric_kind::duration,
     "frontend.g0.publish.enum_sample.name.duration", "Deterministically sampled G0 enum canonical-name preparation duration"},
    {metric_id::frontend_g0_publish_enum_values_duration, metric_kind::duration,
     "frontend.g0.publish.enum_sample.values.duration", "Deterministically sampled G0 enum-value preparation duration"},
    {metric_id::frontend_g0_publish_enum_sample_name_resolve_duration, metric_kind::duration,
     "frontend.g0.publish.enum_sample.name_resolve.duration", "Deterministically sampled enum canonical-name source resolution duration"},
    {metric_id::frontend_g0_publish_enum_sample_name_intern_duration, metric_kind::duration,
     "frontend.g0.publish.enum_sample.name_intern.duration", "Deterministically sampled enum canonical-name String Registry intern duration"},
    {metric_id::frontend_g0_publish_enum_sample_values_resolve_duration, metric_kind::duration,
     "frontend.g0.publish.enum_sample.values_resolve.duration", "Deterministically sampled enum-value source-name resolution duration"},
    {metric_id::frontend_g0_publish_enum_sample_values_intern_duration, metric_kind::duration,
     "frontend.g0.publish.enum_sample.values_intern.duration", "Deterministically sampled enum-value String Registry intern duration"},
    {metric_id::frontend_g0_publish_enum_builder_duration, metric_kind::duration,
     "frontend.g0.publish.enum_builder.duration", "Detailed G0 enum Builder and Graph mutation wall duration"},
    {metric_id::frontend_g0_publish_enum_builder_value_copy_duration, metric_kind::duration,
     "frontend.g0.publish.enum_builder.value_copy.duration", "Detailed enum Builder conversion from canonical enum values into Graph build values"},
    {metric_id::frontend_g0_publish_enum_builder_graph_mutation_duration, metric_kind::duration,
     "frontend.g0.publish.enum_builder.graph_mutation.duration", "Detailed enum Builder call into Graph source replacement canonical mutation"},
    {metric_id::frontend_g0_publish_enum_builder_graph_sample_total_duration, metric_kind::duration,
     "frontend.g0.publish.enum_builder.graph_sample.total.duration", "Sampled total named-enum Graph mutation duration"},

    {metric_id::frontend_g0_publish_enum_builder_graph_sample_identity_duration, metric_kind::duration,
     "frontend.g0.publish.enum_builder.graph_sample.identity.duration", "Sampled stable identity resolution and allocation duration"},
    {metric_id::frontend_g0_publish_enum_builder_graph_sample_contribution_build_duration, metric_kind::duration,
     "frontend.g0.publish.enum_builder.graph_sample.contribution_build.duration", "Sampled enum SourceContribution construction duration"},
    {metric_id::frontend_g0_publish_enum_builder_graph_sample_reconcile_duration, metric_kind::duration,
     "frontend.g0.publish.enum_builder.graph_sample.reconcile.duration", "Sampled retained enum reconciliation duration"},
    {metric_id::frontend_g0_publish_enum_builder_graph_sample_delta_duration, metric_kind::duration,
     "frontend.g0.publish.enum_builder.graph_sample.delta.duration", "Sampled contribution aggregate delta update duration"},
    {metric_id::frontend_g0_publish_enum_builder_graph_sample_contribution_append_duration, metric_kind::duration,
     "frontend.g0.publish.enum_builder.graph_sample.contribution_append.duration", "Sampled SourceContribution candidate append duration"},
    {metric_id::frontend_g0_publish_enum_builder_graph_sample_materialize_duration, metric_kind::duration,
     "frontend.g0.publish.enum_builder.graph_sample.materialize.duration", "Sampled canonical Entity and Type materialization duration"},
    {metric_id::frontend_g0_publish_enum_builder_graph_sample_materialize_state_touch_duration, metric_kind::duration,
     "frontend.g0.publish.enum_builder.graph_sample.materialize.state_touch.duration", "Sampled materialize candidate Entity, contribution and identity touch duration"},
    {metric_id::frontend_g0_publish_enum_builder_graph_sample_materialize_type_storage_duration, metric_kind::duration,
     "frontend.g0.publish.enum_builder.graph_sample.materialize.type_storage.duration", "Sampled materialize Type storage allocation and initialization duration"},
    {metric_id::frontend_g0_publish_enum_builder_graph_sample_materialize_build_state_duration, metric_kind::duration,
     "frontend.g0.publish.enum_builder.graph_sample.materialize.build_state.duration", "Sampled materialize build-state allocation and enum definition copy duration"},
    {metric_id::frontend_g0_publish_enum_builder_graph_sample_materialize_assign_type_duration, metric_kind::duration,
     "frontend.g0.publish.enum_builder.graph_sample.materialize.assign_type.duration", "Sampled materialize canonical type-slot assignment duration"},
    {metric_id::frontend_g0_publish_enum_builder_graph_sample_assign_type_handle_duration, metric_kind::duration,
     "frontend.g0.publish.enum_builder.graph_sample.assign_type.handle.duration", "Sampled type-handle selection and assignment duration"},
    {metric_id::frontend_g0_publish_enum_builder_graph_sample_assign_type_touch_type_duration, metric_kind::duration,
     "frontend.g0.publish.enum_builder.graph_sample.assign_type.touch_type.duration", "Sampled candidate type-slot touch and storage growth duration"},
    {metric_id::frontend_g0_publish_enum_builder_graph_sample_assign_type_candidate_store_duration, metric_kind::duration,
     "frontend.g0.publish.enum_builder.graph_sample.assign_type.candidate_store.duration", "Sampled candidate type replacement store duration"},
    {metric_id::frontend_g0_publish_enum_builder_graph_sample_assign_type_named_type_ref_duration, metric_kind::duration,
     "frontend.g0.publish.enum_builder.graph_sample.assign_type.named_type_ref.duration", "Sampled canonical named TypeRef creation duration"},
    {metric_id::frontend_g0_publish_enum_builder_graph_sample_named_type_ref_existing_lookup_duration, metric_kind::duration,
     "frontend.g0.publish.enum_builder.graph_sample.named_type_ref.existing_lookup.duration", "Sampled existing named TypeRef lookup duration"},
    {metric_id::frontend_g0_publish_enum_builder_graph_sample_named_type_ref_canonical_append_duration, metric_kind::duration,
     "frontend.g0.publish.enum_builder.graph_sample.named_type_ref.canonical_append.duration", "Sampled canonical TypeRef record append duration"},
    {metric_id::frontend_g0_publish_enum_builder_graph_sample_named_type_ref_mapping_append_duration, metric_kind::duration,
     "frontend.g0.publish.enum_builder.graph_sample.named_type_ref.mapping_append.duration", "Sampled type-handle to TypeRef mapping append duration"},
    {metric_id::frontend_g0_publish_enum_builder_graph_sample_named_type_ref_index_emplace_duration, metric_kind::duration,
     "frontend.g0.publish.enum_builder.graph_sample.named_type_ref.index_emplace.duration", "Sampled named TypeRef hash-index emplace duration"},
    {metric_id::frontend_g0_publish_enum_builder_graph_sample_materialize_attach_duration, metric_kind::duration,
     "frontend.g0.publish.enum_builder.graph_sample.materialize.attach.duration", "Sampled materialize candidate build-state attachment duration"},

    {metric_id::frontend_g0_publish_enum_builder_graph_call_count, metric_kind::counter,
     "frontend.g0.publish.enum_builder.graph.call.count", "Named enum Graph mutation calls observed by sampled telemetry"},
    {metric_id::frontend_g0_publish_enum_builder_graph_sample_count, metric_kind::counter,
     "frontend.g0.publish.enum_builder.graph.sample.count", "Named enum Graph mutation calls sampled at stride 1024"},
    {metric_id::frontend_g0_publish_enum_builder_residual_duration, metric_kind::duration,
     "frontend.g0.publish.enum_builder.residual.duration", "Detailed enum Builder residual outside value copy and Graph mutation"},
    {metric_id::frontend_g0_publish_aggregate_builder_duration, metric_kind::duration,
     "frontend.g0.publish.aggregate_builder.duration", "Detailed G0 aggregate Builder and Graph mutation wall duration"},
    {metric_id::frontend_g0_publish_residual_duration, metric_kind::duration,
     "frontend.g0.publish.residual.duration", "G0 publication residual: source-name resolution, String Registry interning, scratch materialization and loop orchestration"},
    {metric_id::frontend_g0_publish_source_count, metric_kind::counter,
     "frontend.g0.publish.source.count", "Detailed number of Source replacement publications"},
    {metric_id::frontend_g0_publish_enum_builder_count, metric_kind::counter,
     "frontend.g0.publish.enum_builder.count", "Detailed number of enum Builder operations"},
    {metric_id::frontend_g0_publish_aggregate_builder_count, metric_kind::counter,
     "frontend.g0.publish.aggregate_builder.count", "Detailed number of aggregate Builder operations"},
    {metric_id::frontend_g0_commit_duration, metric_kind::duration,
     "frontend.g0.commit.duration", "G0 transaction commit wall duration"},
    {metric_id::frontend_g0_tx_source_prepare_duration, metric_kind::duration,
     "frontend.g0.tx.source_prepare.duration", "G0 Source Manager transaction prepare wall duration"},
    {metric_id::frontend_g0_tx_string_prepare_duration, metric_kind::duration,
     "frontend.g0.tx.string_prepare.duration", "G0 String Registry transaction prepare wall duration"},
    {metric_id::frontend_g0_tx_graph_prepare_duration, metric_kind::duration,
     "frontend.g0.tx.graph_prepare.duration", "G0 Graph transaction prepare wall duration"},
    {metric_id::frontend_g0_graph_pending_member_resolution_duration, metric_kind::duration,
     "frontend.g0.graph.pending_member_resolution.duration", "G0 pending member TypeRef resolution wall duration"},
    {metric_id::frontend_g0_graph_live_typeref_validation_duration, metric_kind::duration,
     "frontend.g0.graph.live_typeref_validation.duration", "G0 live TypeRef validation wall duration"},
    {metric_id::frontend_g0_graph_canonical_typeref_rebuild_duration, metric_kind::duration,
     "frontend.g0.graph.canonical_typeref_rebuild.duration", "G0 canonical TypeRef rebuild wall duration"},
    {metric_id::frontend_g0_graph_string_validation_duration, metric_kind::duration,
     "frontend.g0.graph.string_validation.duration", "G0 Graph string validation wall duration"},
    {metric_id::frontend_g0_graph_definition_scan_duration, metric_kind::duration,
     "frontend.g0.graph.definition_scan.duration", "G0 definition scan wall duration"},
    {metric_id::frontend_g0_graph_definition_materialization_duration, metric_kind::duration,
     "frontend.g0.graph.definition_materialization.duration", "G0 definition materialization wall duration"},
    {metric_id::frontend_g0_graph_rebuild_storage_duration, metric_kind::duration,
     "frontend.g0.graph.rebuild_storage.duration", "G0 Graph rebuild storage wall duration"},
    {metric_id::frontend_g0_graph_dependency_index_duration, metric_kind::duration,
     "frontend.g0.graph.dependency_index.duration", "G0 Graph dependency index wall duration"},
    {metric_id::frontend_g0_graph_final_prepare_duration, metric_kind::duration,
     "frontend.g0.graph.final_prepare.duration", "G0 Graph final prepare wall duration"},
    {metric_id::frontend_g0_tx_string_retention_duration, metric_kind::duration,
     "frontend.g0.tx.string_retention.duration", "G0 String Registry retention wall duration"},
    {metric_id::frontend_g0_tx_string_compaction_duration, metric_kind::duration,
     "frontend.g0.tx.string_compaction.duration", "G0 String Registry compaction wall duration"},
    {metric_id::frontend_g0_tx_contribution_prepare_duration, metric_kind::duration,
     "frontend.g0.tx.contribution_prepare.duration", "G0 SourceContribution prepare wall duration"},
    {metric_id::frontend_g0_tx_source_publish_duration, metric_kind::duration,
     "frontend.g0.tx.source_publish.duration", "G0 Source Manager publish wall duration"},
    {metric_id::frontend_g0_tx_string_publish_duration, metric_kind::duration,
     "frontend.g0.tx.string_publish.duration", "G0 String Registry publish wall duration"},
    {metric_id::frontend_g0_tx_contribution_publish_duration, metric_kind::duration,
     "frontend.g0.tx.contribution_publish.duration", "G0 SourceContribution publish wall duration"},
    {metric_id::frontend_g0_tx_graph_publish_duration, metric_kind::duration,
     "frontend.g0.tx.graph_publish.duration", "G0 Graph publish wall duration"},
    {metric_id::frontend_cache_publish_duration, metric_kind::duration,
     "frontend.cache_publish.duration", "Frontend cache publication wall duration"},
    {metric_id::source_tracker_init_duration, metric_kind::duration,
     "source.tracker.init.duration", "Source change tracker initialization wall duration"},
    {metric_id::source_acquisition_count, metric_kind::counter,
     "source.acquisition.count", "Number of physical source acquisition attempts"},
    {metric_id::source_acquisition_duration, metric_kind::duration,
     "source.acquisition.duration", "Total duration of physical source acquisition attempts"},
    {metric_id::source_file_open_duration, metric_kind::duration,
     "source.acquisition.open.duration", "Duration of opening source files"},
    {metric_id::source_observe_before_duration, metric_kind::duration,
     "source.acquisition.observe_before.duration", "Duration of source observation before reading"},
    {metric_id::source_read_duration, metric_kind::duration,
     "source.acquisition.read.duration", "Duration of reading source content"},
    {metric_id::source_observe_after_duration, metric_kind::duration,
     "source.acquisition.observe_after.duration", "Duration of source observation after reading"},
    {metric_id::source_sha256_duration, metric_kind::duration,
     "source.acquisition.sha256.duration", "Duration of source SHA-256 computation"},
    {metric_id::source_candidate_update_duration, metric_kind::duration,
     "source.acquisition.candidate_update.duration", "Duration of candidate physical-state update"},
    {metric_id::source_unchanged_fast_path_count, metric_kind::counter,
     "source.acquisition.unchanged_fast_path.count", "Number of acquisitions completed by equal-observation fast path"},
    {metric_id::source_content_read_count, metric_kind::counter,
     "source.acquisition.content_read.count", "Number of source contents read, including empty files"},
    {metric_id::source_candidate_added_count, metric_kind::counter,
     "source.candidate.added.count", "Number of final added source candidates observed"},
    {metric_id::source_candidate_modified_count, metric_kind::counter,
     "source.candidate.modified.count", "Number of final modified source candidates observed"},
    {metric_id::source_candidate_removed_count, metric_kind::counter,
     "source.candidate.removed.count", "Number of final removed source candidates observed"},
    {metric_id::source_candidate_observation_only_count, metric_kind::counter,
     "source.candidate.observation_only.count", "Number of final observation-only source candidates observed"},
    {metric_id::source_acquisition_failure_count, metric_kind::counter,
     "source.acquisition.failure.count", "Number of failed physical source acquisitions"},
    {metric_id::source_toctou_rejection_count, metric_kind::counter,
     "source.acquisition.toctou_rejection.count", "Number of acquisitions rejected after observation changed while reading"},
    {metric_id::source_bytes_read, metric_kind::counter,
     "source.acquisition.bytes_read", "Exact number of source bytes read"},
    {metric_id::source_checkpoint_save_attempt_count, metric_kind::counter, "source.checkpoint.save.attempt.count", "Source checkpoint save attempts"},
    {metric_id::source_checkpoint_save_success_count, metric_kind::counter, "source.checkpoint.save.success.count", "Successful source checkpoint saves"},
    {metric_id::source_checkpoint_save_failure_count, metric_kind::counter, "source.checkpoint.save.failure.count", "Failed source checkpoint saves"},
    {metric_id::source_checkpoint_source_count, metric_kind::counter, "source.checkpoint.source.count", "Sources serialized into checkpoints"},
    {metric_id::source_checkpoint_root_count, metric_kind::counter, "source.checkpoint.root.count", "Roots serialized into checkpoints"},
    {metric_id::source_checkpoint_forward_edge_count, metric_kind::counter, "source.checkpoint.forward_edge.count", "Forward dependency edges serialized"},
    {metric_id::source_checkpoint_reverse_edge_count, metric_kind::counter, "source.checkpoint.reverse_edge.count", "Reverse dependency edges serialized"},
    {metric_id::source_checkpoint_path_bytes, metric_kind::counter, "source.checkpoint.path.bytes", "WTF-8 path bytes serialized"},
    {metric_id::source_checkpoint_path_index_capacity, metric_kind::counter, "source.checkpoint.path_index.capacity", "Path index buckets serialized"},
    {metric_id::source_checkpoint_artifact_bytes, metric_kind::counter, "source.checkpoint.artifact.bytes", "Checkpoint artifact bytes produced"},
    {metric_id::source_checkpoint_bytes_hashed, metric_kind::counter, "source.checkpoint.hashed.bytes", "Checkpoint payload bytes hashed"},
    {metric_id::source_checkpoint_bytes_written, metric_kind::counter, "source.checkpoint.written.bytes", "Temporary checkpoint bytes written"},
    {metric_id::source_checkpoint_save_duration, metric_kind::duration, "source.checkpoint.save.duration", "Complete checkpoint save duration"},
    {metric_id::source_checkpoint_snapshot_layout_duration, metric_kind::duration, "source.checkpoint.snapshot_layout.duration", "Checkpoint snapshot and layout preparation duration"},
    {metric_id::source_checkpoint_path_materialization_duration, metric_kind::duration, "source.checkpoint.path_materialization.duration", "WTF-8 path materialization duration"},
    {metric_id::source_checkpoint_path_index_duration, metric_kind::duration, "source.checkpoint.path_index.duration", "Path index construction duration"},
    {metric_id::source_checkpoint_source_state_duration, metric_kind::duration, "source.checkpoint.source_state.duration", "SourceCore and PhysicalState materialization duration"},
    {metric_id::source_checkpoint_forward_csr_duration, metric_kind::duration, "source.checkpoint.forward_csr.duration", "Forward CSR materialization duration"},
    {metric_id::source_checkpoint_reverse_csr_duration, metric_kind::duration, "source.checkpoint.reverse_csr.duration", "Reverse CSR materialization duration"},
    {metric_id::source_checkpoint_payload_sha256_duration, metric_kind::duration, "source.checkpoint.payload_sha256.duration", "Checkpoint payload SHA-256 duration"},
    {metric_id::source_checkpoint_write_duration, metric_kind::duration, "source.checkpoint.write.duration", "Temporary checkpoint write duration"},
    {metric_id::source_checkpoint_flush_duration, metric_kind::duration, "source.checkpoint.flush.duration", "Checkpoint FlushFileBuffers duration"},
    {metric_id::source_checkpoint_reopen_map_duration, metric_kind::duration, "source.checkpoint.reopen_map.duration", "Checkpoint validation reopen and map duration"},
    {metric_id::source_checkpoint_artifact_validation_duration, metric_kind::duration, "source.checkpoint.artifact_validation.duration", "Checkpoint artifact validation duration"},
    {metric_id::source_checkpoint_deep_validation_duration, metric_kind::duration, "source.checkpoint.deep_validation.duration", "Checkpoint deep semantic validation duration"},
    {metric_id::compiled_save_total_duration, metric_kind::duration, "compiled.save.total", "Compiled checkpoint save duration"},
    {metric_id::compiled_save_materialization_duration, metric_kind::duration, "compiled.save.materialization", "Compiled checkpoint materialization duration"},
    {metric_id::compiled_save_hash_duration, metric_kind::duration, "compiled.save.hash", "Compiled checkpoint hashing duration"},
    {metric_id::compiled_save_write_duration, metric_kind::duration, "compiled.save.write", "Compiled checkpoint write duration"},
    {metric_id::compiled_save_flush_duration, metric_kind::duration, "compiled.save.flush", "Compiled checkpoint flush duration"},
    {metric_id::compiled_load_total_duration, metric_kind::duration, "compiled.load.total", "Compiled checkpoint load duration"},
    {metric_id::compiled_load_open_duration, metric_kind::duration, "compiled.load.open", "Compiled checkpoint open/read duration"},
    {metric_id::compiled_load_validate_duration, metric_kind::duration, "compiled.load.validate", "Compiled checkpoint validation duration"},
    {metric_id::compiled_load_strings_duration, metric_kind::duration, "compiled.load.strings", "String registry reconstruction duration"},
    {metric_id::compiled_load_graph_duration, metric_kind::duration, "compiled.load.graph", "Graph reconstruction duration"},
    {metric_id::compiled_load_publish_duration, metric_kind::duration, "compiled.load.publish", "Compiled candidate publication duration"},
    {metric_id::compiled_artifact_bytes, metric_kind::counter, "compiled.artifact.bytes", "Compiled artifact bytes"},
    {metric_id::compiled_string_count, metric_kind::counter, "compiled.string.count", "Compiled strings"},
    {metric_id::compiled_entity_slot_count, metric_kind::counter, "compiled.entity_slot.count", "Compiled entity slots"},
    {metric_id::compiled_type_slot_count, metric_kind::counter, "compiled.type_slot.count", "Compiled type slots"},
    {metric_id::compiled_enum_value_count, metric_kind::counter, "compiled.enum_value.count", "Compiled enum values"},
    {metric_id::runtime_attach_count, metric_kind::counter,
     "runtime.attach.count", "Number of Runtime attachment attempts"},
    {metric_id::runtime_attach_duration, metric_kind::duration,
     "runtime.attach.duration", "Duration of Runtime attachment attempts"},
    {metric_id::shm_initializations, metric_kind::counter,
     "shm.initializations", "Number of Shared Memory initialization attempts"},
    {metric_id::shm_initialization_duration, metric_kind::duration,
     "shm.initialization.duration", "Duration of Shared Memory initialization attempts"},
}};

[[nodiscard]] constexpr const metric_descriptor& descriptor(metric_id id) noexcept
{
    return metric_descriptors[metric_index(id)];
}

consteval bool metric_registry_is_valid()
{
    if (metric_descriptors.size() != metric_count)
    {
        return false;
    }

    for (std::size_t index = 0; index < metric_descriptors.size(); ++index)
    {
        if (metric_index(metric_descriptors[index].id) != index)
        {
            return false;
        }
    }
    return true;
}

static_assert(metric_registry_is_valid());

} // namespace cw::server
