#include "graph.hpp"
#include "compiled_state.hpp"
#include "../source/source_manager.hpp"
#include "../string/string_registry.hpp"
#include <algorithm>
#include <array>
#include <cassert>
#include <limits>
#include <new>
#include <stdexcept>
#include <utility>

namespace cw::server
{
namespace { constexpr std::size_t builtin_count=static_cast<std::size_t>(builtin_type::long_double_floating)+1;
std::uint64_t mask(std::uint8_t w) noexcept { return w==64?~std::uint64_t{}:(std::uint64_t{1}<<w)-1; }
bool fits(integral_constant v,builtin_type target,const abi_configuration& abi) noexcept
{
 const auto sw=builtin_bit_width(v.type,abi),tw=builtin_bit_width(target,abi);
 if(!sw||!tw||!is_integral(v.type)||!is_integral(target)) return false;
 if(builtin_is_signed(v.type,abi)) { const auto s=sw==64?static_cast<std::int64_t>(v.bits):static_cast<std::int64_t>(v.bits<<(64-sw))>>(64-sw);
  if(builtin_is_signed(target,abi)){if(tw==64)return true; return s>=-(std::int64_t{1}<<(tw-1))&&s<=(std::int64_t{1}<<(tw-1))-1;} return s>=0&&static_cast<std::uint64_t>(s)<=mask(tw);}
 if(builtin_is_signed(target,abi)) return tw==64?v.bits<=static_cast<std::uint64_t>(std::numeric_limits<std::int64_t>::max()):v.bits<(std::uint64_t{1}<<(tw-1));
 return v.bits<=mask(tw);
}

std::uint64_t convert(integral_constant v,builtin_type target,const abi_configuration& abi) noexcept
{ auto x=v.bits; const auto sw=builtin_bit_width(v.type,abi); if(builtin_is_signed(v.type,abi)){const auto s=sw==64?static_cast<std::int64_t>(v.bits):static_cast<std::int64_t>(v.bits<<(64-sw))>>(64-sw);x=static_cast<std::uint64_t>(s);} return x&mask(builtin_bit_width(target,abi)); }
}

std::size_t graph::derived_type_key_hash::operator()(const derived_type_key& k)const noexcept
{auto h=static_cast<std::size_t>(k.child.value())*0x9e3779b1u;h^=static_cast<std::size_t>(k.kind)+0x9e3779b9u+(h<<6)+(h>>2);h^=static_cast<std::size_t>(k.payload^(k.payload>>32))+0x9e3779b9u+(h<<6)+(h>>2);return h;}

struct graph::definition_payload { builtin_type underlying=builtin_type::integer; std::vector<enum_value_record> values; };
struct graph::source_contribution { stable_id entity{}; string_id name{}; entity_kind kind=entity_kind::enum_type; enum_definition_state state=enum_definition_state::opaque; bool scoped=false,fixed=false; builtin_type underlying=builtin_type::integer; std::shared_ptr<const definition_payload> definition; };
struct graph::source_state { std::vector<source_contribution> named; std::vector<std::uint32_t> anonymous_types; };
struct graph::enum_aggregate { std::uint32_t declarations=0,scoped=0,unscoped=0,fixed=0,nonfixed=0,definitions=0,active_fixed=0,aggregate_declarations=0,aggregate_definitions=0; std::array<std::uint32_t,builtin_count> underlying{}; builtin_type active_type=builtin_type::integer; source_id definition_source{}; std::shared_ptr<const definition_payload> definition; source_id aggregate_definition_source{}; };
struct graph::type_storage { user_type_record record; std::vector<enum_value_record> enumerators; std::vector<member_record> members; std::uint32_t member_begin=0,member_count=0; bool anonymous=false; source_id anonymous_source{}; };
struct graph::entity_slot { entity_record record{}; bool live=false; };
struct graph::candidate_identity_slot { std::uint64_t generation=0; stable_id value{}; };
struct graph::candidate_entity_slot { std::uint64_t generation=0; entity_slot entity; enum_aggregate aggregate; };
enum class candidate_type_kind:std::uint8_t{unchanged,replacement,removed};
struct graph::candidate_type_slot { std::uint64_t generation=0; candidate_type_kind kind=candidate_type_kind::unchanged; std::unique_ptr<type_storage> value; };
struct graph::candidate_source_slot { std::uint64_t generation=0; source_state value; };

graph::graph()=default; graph::~graph()=default;
status graph::initialize(abi_configuration abi) noexcept {try{types_.clear();free_type_slots_.clear();entities_.clear();identity_.clear();enum_aggregates_.clear();source_states_.clear();members_.clear();canonical_types_.clear();canonical_types_.push_back({});for(std::uint32_t i=0;i<=static_cast<std::uint32_t>(builtin_type::void_type);++i){canonical_type_record r;r.kind=canonical_type_kind::builtin;r.builtin=static_cast<builtin_type>(i);canonical_types_.push_back(r);}named_type_refs_.clear();derived_type_index_.clear();candidate_identities_.clear();candidate_entities_.clear();candidate_types_.clear();candidate_sources_.clear();entity_count_=0;user_type_count_=0;next_stable_id_=1;next_candidate_generation_=1;abi_=abi;++generation_;return{};}catch(...){return{status_code::initialization_failed};} }
graph_update graph::begin_update() noexcept { auto cg=next_candidate_generation_++; if(!cg) cg=next_candidate_generation_++; return graph_update{*this,generation_,cg}; }
const entity_record* graph::find(string_id n)const noexcept{return n&&n.value()<identity_.size()?find(identity_[n.value()]):nullptr;}
const entity_record* graph::find(stable_id id)const noexcept{return id&&id.value()<entities_.size()&&entities_[id.value()].live?&entities_[id.value()].record:nullptr;}
const user_type_record* graph::find(type_handle h)const noexcept{return h&&h.value()<=types_.size()&&types_[h.value()-1]?&types_[h.value()-1]->record:nullptr;}
std::span<const enum_value_record> graph::enum_values(type_handle h)const noexcept{return h&&h.value()<=types_.size()&&types_[h.value()-1]?std::span<const enum_value_record>{types_[h.value()-1]->enumerators}:std::span<const enum_value_record>{};}
std::span<const member_record> graph::members(type_handle h)const noexcept{if(!h||h.value()>types_.size()||!types_[h.value()-1]||types_[h.value()-1]->record.kind!=user_type_kind::aggregate)return{};const auto b=types_[h.value()-1]->member_begin,n=types_[h.value()-1]->member_count;if(b>members_.size()||n>members_.size()-b)return{};return{members_.data()+b,n};}
const member_record* graph::member(type_handle h,member_index i)const noexcept{const auto values=members(h);return i&&i.value()<=values.size()?&values[i.value()-1]:nullptr;}
member_index graph::find_member(type_handle h,string_id name)const noexcept{const auto values=members(h);for(std::uint32_t i=0;i<values.size();++i)if(values[i].name==name)return member_index{i+1};return{};}
canonical_type_kind graph::kind(TypeRef r)const noexcept{return r&&r.value()<canonical_types_.size()?canonical_types_[r.value()].kind:canonical_type_kind::builtin;}
bool graph::builtin(TypeRef r,builtin_type& out)const noexcept{if(!r||r.value()>=canonical_types_.size()||canonical_types_[r.value()].kind!=canonical_type_kind::builtin)return false;out=canonical_types_[r.value()].builtin;return true;}
bool graph::named(TypeRef r,type_handle& out)const noexcept{out={};if(!r||r.value()>=canonical_types_.size()||canonical_types_[r.value()].kind!=canonical_type_kind::named)return false;out=canonical_types_[r.value()].named;return true;}
const derived_type_record* graph::derived(TypeRef r)const noexcept{return r&&r.value()<canonical_types_.size()&&canonical_types_[r.value()].kind==canonical_type_kind::derived?&canonical_types_[r.value()].derived:nullptr;}
std::size_t graph::derived_type_count()const noexcept{return derived_type_index_.size();}
std::size_t graph::contribution_count(source_id s)const noexcept{return s.value()<source_states_.size()?source_states_[s.value()].named.size():0;}

status graph::export_compiled(compiled_graph_state& output) const noexcept
{
 try{
  compiled_graph_state candidate;candidate.abi=abi_;candidate.identities.reserve(identity_.size());for(auto id:identity_)candidate.identities.push_back(id.value());
  candidate.entities.resize(entities_.size());for(std::size_t i=0;i<entities_.size();++i){auto& d=candidate.entities[i];const auto&s=entities_[i];d.live=s.live;d.kind=s.record.kind;d.id=s.record.id.value();d.name=s.record.name.value();d.defining_source=s.record.defining_source.value();d.type=s.record.type.value();}
  candidate.types.resize(types_.size());for(std::size_t i=0;i<types_.size();++i)if(types_[i]){auto& d=candidate.types[i];d.live=true;d.record=types_[i]->record;d.anonymous=types_[i]->anonymous;d.anonymous_source=types_[i]->anonymous_source;d.member_begin=types_[i]->member_begin;d.member_count=types_[i]->member_count;d.enumerators.reserve(types_[i]->enumerators.size());for(const auto&v:types_[i]->enumerators)d.enumerators.push_back({v.name.value(),v.bits});}
  candidate.members.reserve(members_.size());for(const auto& m:members_)candidate.members.push_back({m.name.value(),m.type.value()});
  candidate.canonical_types.reserve(canonical_types_.size());for(const auto& t:canonical_types_)candidate.canonical_types.push_back({static_cast<std::uint8_t>(t.kind),static_cast<std::uint8_t>(t.builtin),t.named.value(),t.derived.child.value(),t.derived.payload});
  output=std::move(candidate);return{};
 }catch(...){return{status_code::initialization_failed};}
}

status graph::import_compiled(const compiled_graph_state& input) noexcept
{
 try{
  if(input.abi.target!=abi_target::windows_x64||input.abi.pack==0)return{status_code::artifact_corrupt};
  std::vector<entity_slot> entities(input.entities.size());std::vector<enum_aggregate> aggregates(input.entities.size());
  std::vector<member_record> imported_members; imported_members.reserve(input.members.size()); for(const auto& m:input.members){if(!m.name||!m.type_ref)return{status_code::artifact_corrupt}; imported_members.push_back({string_id{m.name},TypeRef{m.type_ref}});}
  std::vector<std::unique_ptr<type_storage>> types(input.types.size());std::vector<std::uint32_t> free_types;
  std::size_t entity_count=0,type_count=0;
  for(std::size_t i=0;i<input.types.size();++i){const auto& s=input.types[i];if(!s.live){free_types.push_back(static_cast<std::uint32_t>(i+1));continue;}if(s.record.kind!=user_type_kind::aggregate&&s.record.kind!=user_type_kind::enumeration)return{status_code::artifact_corrupt};if(s.record.kind==user_type_kind::aggregate&&!s.enumerators.empty())return{status_code::artifact_corrupt};if(s.record.kind==user_type_kind::enumeration&&s.record.enumeration.enumerator_count!=s.enumerators.size())return{status_code::artifact_corrupt};auto p=std::make_unique<type_storage>();p->record=s.record;p->anonymous=s.anonymous;p->anonymous_source=s.anonymous_source;p->enumerators.reserve(s.enumerators.size());for(const auto&v:s.enumerators){enum_value_record value;value.name=string_id{v.name};value.bits=v.bits;p->enumerators.push_back(value);}types[i]=std::move(p);++type_count;}
  for(std::size_t i=0;i<input.entities.size();++i){const auto& s=input.entities[i];entities[i].live=s.live;auto&r=entities[i].record;r.id=stable_id{s.id};r.kind=s.kind;r.name=string_id{s.name};r.defining_source=source_id{s.defining_source};r.type=type_handle{s.type};if(!s.live)continue;if(i==0||s.id!=i||!s.name||!s.type||s.type>types.size()||!types[s.type-1])return{status_code::artifact_corrupt};if((s.kind==entity_kind::aggregate_type)!=(types[s.type-1]->record.kind==user_type_kind::aggregate))return{status_code::artifact_corrupt};++entity_count;}
  std::vector<stable_id> identities;identities.reserve(input.identities.size());for(std::size_t i=0;i<input.identities.size();++i){const auto id=input.identities[i];if(id&&(id>=entities.size()||!entities[id].live||entities[id].record.name.value()!=i))return{status_code::artifact_corrupt};identities.push_back(stable_id{id});}
  for(std::size_t i=0;i<input.types.size();++i)if(types[i]){types[i]->member_begin=input.types[i].member_begin;types[i]->member_count=input.types[i].member_count;if(types[i]->member_begin>imported_members.size()||types[i]->member_count>imported_members.size()-types[i]->member_begin)return{status_code::artifact_corrupt};}
  types_.swap(types);free_type_slots_.swap(free_types);entities_.swap(entities);identity_.swap(identities);enum_aggregates_.swap(aggregates);source_states_.clear();members_.swap(imported_members);canonical_types_.clear();canonical_types_.push_back({});for(std::uint32_t i=0;i<=static_cast<std::uint32_t>(builtin_type::void_type);++i){canonical_type_record r;r.kind=canonical_type_kind::builtin;r.builtin=static_cast<builtin_type>(i);canonical_types_.push_back(r);}named_type_refs_.assign(types_.size()+1,{});for(std::uint32_t h=1;h<=types_.size();++h)if(types_[h-1]){canonical_type_record r;r.kind=canonical_type_kind::named;r.named=type_handle{h};const auto raw=static_cast<std::uint32_t>(canonical_types_.size());canonical_types_.push_back(r);named_type_refs_[h]=TypeRef{raw};}for(std::size_t i=canonical_types_.size();i<input.canonical_types.size();++i){const auto& x=input.canonical_types[i];if(x.kind!=static_cast<std::uint8_t>(canonical_type_kind::derived)||!x.child||x.child>=canonical_types_.size())return{status_code::artifact_corrupt};canonical_type_record r;r.kind=canonical_type_kind::derived;r.derived={static_cast<derived_type_kind>(x.builtin),TypeRef{x.child},x.payload};canonical_types_.push_back(r);derived_type_index_[{r.derived.kind,r.derived.child,r.derived.payload}]=TypeRef{static_cast<std::uint32_t>(i)};}candidate_identities_.clear();candidate_entities_.clear();candidate_types_.clear();candidate_sources_.clear();entity_count_=entity_count;user_type_count_=type_count;next_stable_id_=static_cast<std::uint32_t>(entities_.size());if(next_stable_id_==0)next_stable_id_=1;next_candidate_generation_=1;abi_=input.abi;++generation_;return{};
 }catch(...){return{status_code::initialization_failed};}
}

void graph::swap_compiled(graph& other) noexcept
{types_.swap(other.types_);free_type_slots_.swap(other.free_type_slots_);entities_.swap(other.entities_);identity_.swap(other.identity_);enum_aggregates_.swap(other.enum_aggregates_);source_states_.swap(other.source_states_);members_.swap(other.members_);canonical_types_.swap(other.canonical_types_);named_type_refs_.swap(other.named_type_refs_);derived_type_index_.swap(other.derived_type_index_);candidate_identities_.swap(other.candidate_identities_);candidate_entities_.swap(other.candidate_entities_);candidate_types_.swap(other.candidate_types_);candidate_sources_.swap(other.candidate_sources_);std::swap(entity_count_,other.entity_count_);std::swap(user_type_count_,other.user_type_count_);std::swap(next_stable_id_,other.next_stable_id_);std::swap(generation_,other.generation_);std::swap(abi_,other.abi_);std::swap(next_candidate_generation_,other.next_candidate_generation_);}

graph_update::graph_update(graph& o,std::uint64_t g,std::uint64_t cg)noexcept:owner_(&o),next_stable_id_(o.next_stable_id_),next_type_slot_(static_cast<std::uint32_t>(o.types_.size()+1)),base_generation_(g),candidate_generation_(cg){}
graph_update::~graph_update()=default;
graph_update::graph_update(graph_update&& x)noexcept:owner_(std::exchange(x.owner_,nullptr)),owned_types_(std::move(x.owned_types_)),changed_identities_(std::move(x.changed_identities_)),changed_entities_(std::move(x.changed_entities_)),changed_types_(std::move(x.changed_types_)),changed_sources_(std::move(x.changed_sources_)),claimed_free_type_slots_(std::move(x.claimed_free_type_slots_)),added_canonical_types_(std::move(x.added_canonical_types_)),added_named_type_refs_(std::move(x.added_named_type_refs_)),added_named_type_index_(std::move(x.added_named_type_index_)),added_derived_type_index_(std::move(x.added_derived_type_index_)),next_stable_id_(x.next_stable_id_),next_type_slot_(x.next_type_slot_),base_generation_(x.base_generation_),candidate_generation_(x.candidate_generation_),failure_(x.failure_),prepared_(x.prepared_),committed_(x.committed_){}

graph::candidate_identity_slot& graph_update::touch_identity(std::uint32_t n){if(owner_->candidate_identities_.size()<=n)owner_->candidate_identities_.resize(n+1);auto& s=owner_->candidate_identities_[n];if(s.generation!=candidate_generation_){s.generation=candidate_generation_;s.value=n<owner_->identity_.size()?owner_->identity_[n]:stable_id{};changed_identities_.push_back(n);}return s;}
graph::candidate_entity_slot& graph_update::touch_entity(std::uint32_t id){if(owner_->candidate_entities_.size()<=id)owner_->candidate_entities_.resize(id+1);auto& s=owner_->candidate_entities_[id];if(s.generation!=candidate_generation_){s.generation=candidate_generation_;s.entity=id<owner_->entities_.size()?owner_->entities_[id]:graph::entity_slot{};s.aggregate=id<owner_->enum_aggregates_.size()?owner_->enum_aggregates_[id]:graph::enum_aggregate{};changed_entities_.push_back(id);}return s;}
graph::candidate_type_slot& graph_update::touch_type(std::uint32_t h){if(owner_->candidate_types_.size()<=h)owner_->candidate_types_.resize(h+1);auto& s=owner_->candidate_types_[h];if(s.generation!=candidate_generation_){s.generation=candidate_generation_;s.kind=candidate_type_kind::unchanged;s.value.reset();changed_types_.push_back(h);}return s;}
graph::candidate_source_slot& graph_update::touch_source(std::uint32_t id){if(owner_->candidate_sources_.size()<=id)owner_->candidate_sources_.resize(id+1);auto& s=owner_->candidate_sources_[id];if(s.generation!=candidate_generation_){s.generation=candidate_generation_;s.value={};changed_sources_.push_back(id);}return s;}

status graph_update::replace_source(source_id s,source_replacement& out)noexcept
{out.update_=nullptr;out.source_={};if(!failure_.ok())return failure_;if(!owner_||prepared_||committed_||!s)return failure_={status_code::invalid_state};if(s.value()<owner_->candidate_sources_.size()&&owner_->candidate_sources_[s.value()].generation==candidate_generation_)return failure_={status_code::duplicate_source_replacement};auto r=begin_source_replacement(s);if(!r.ok())return r;out.update_=this;out.source_=s;return{};}
status graph_update::source_replacement::add_named_enum(string_id n,const enum_build_data& d,stable_id& e,type_handle& t)noexcept{return update_?update_->declare_named_enum(n,source_,d,e,t):status{status_code::invalid_state};}
status graph_update::source_replacement::add_anonymous_enum(const enum_build_data& d,type_handle& t)noexcept{return update_?update_->add_anonymous_enum(source_,d,t):status{status_code::invalid_state};}
status graph_update::source_replacement::add_named_type(string_id n,aggregate_definition_state s,stable_id& e,type_handle& t)noexcept{return update_?update_->declare_named_type(n,source_,s,e,t):status{status_code::invalid_state};}

status graph_update::source_replacement::define_members(type_handle h,std::span<const member_build> input)noexcept
{if(!update_||!h)return{status_code::invalid_state};try{auto& slot=update_->touch_type(h.value());if(slot.kind!=candidate_type_kind::replacement||!slot.value||slot.value->record.kind!=user_type_kind::aggregate||slot.value->record.aggregate.definition_state!=aggregate_definition_state::defined)return update_->failure_={status_code::configuration_failed};std::unordered_set<std::uint32_t> names;std::vector<member_record> values;values.reserve(input.size());for(const auto&m:input){if(!m.name||!m.type.valid()||!names.insert(m.name.value()).second)return update_->failure_={status_code::configuration_failed};values.push_back({m.name,m.type});}slot.value->members=std::move(values);return{};}catch(...){return update_->failure_={status_code::initialization_failed};}}

TypeRef graph_update::source_replacement::builtin_type_ref(builtin_type value)const noexcept
{const auto raw=static_cast<std::uint32_t>(value)+1;return update_&&raw<update_->owner_->canonical_types_.size()?TypeRef{raw}:TypeRef{};}
status graph_update::source_replacement::resolve_type(string_id name,TypeRef& result)const noexcept
{result={};if(!update_||!name)return{status_code::invalid_state};const auto* entity=update_->find(name);if(!entity)return{status_code::configuration_failed};return update_->get_or_create_named_type_ref(entity->type,result);}
status graph_update::source_replacement::get_or_create_pointer(TypeRef child,TypeRef& out)noexcept{return update_?update_->get_or_create_derived(derived_type_kind::pointer,child,0,out):status{status_code::invalid_state};}
status graph_update::source_replacement::get_or_create_array(TypeRef child,std::uint64_t extent,TypeRef& out)noexcept{return update_?update_->get_or_create_derived(derived_type_kind::array,child,extent,out):status{status_code::invalid_state};}
status graph_update::source_replacement::get_or_create_lvalue_reference(TypeRef child,TypeRef& out)noexcept{return update_?update_->get_or_create_derived(derived_type_kind::lvalue_reference,child,0,out):status{status_code::invalid_state};}
status graph_update::source_replacement::get_or_create_rvalue_reference(TypeRef child,TypeRef& out)noexcept{return update_?update_->get_or_create_derived(derived_type_kind::rvalue_reference,child,0,out):status{status_code::invalid_state};}

status graph_update::get_or_create_named_type_ref(type_handle handle,TypeRef& out)noexcept
{out={};if(!handle)return{status_code::configuration_failed};if(handle.value()<owner_->named_type_refs_.size()&&owner_->named_type_refs_[handle.value()]){out=owner_->named_type_refs_[handle.value()];return{};}if(auto i=added_named_type_index_.find(handle.value());i!=added_named_type_index_.end()){out=i->second;return{};}try{const auto raw=owner_->canonical_types_.size()+added_canonical_types_.size();if(raw>std::numeric_limits<std::uint32_t>::max())return failure_={status_code::initialization_failed};out=TypeRef{static_cast<std::uint32_t>(raw)};graph::canonical_type_record r;r.kind=canonical_type_kind::named;r.named=handle;added_canonical_types_.push_back(r);added_named_type_refs_.push_back({handle.value(),out});added_named_type_index_.emplace(handle.value(),out);return{};}catch(...){return failure_={status_code::initialization_failed};}}

status graph_update::get_or_create_derived(derived_type_kind kind,TypeRef child,std::uint64_t payload,TypeRef& out)noexcept
{out={};if(!child||(kind!=derived_type_kind::array&&payload!=0)||(kind==derived_type_kind::array&&payload==0))return failure_={status_code::configuration_failed};const graph::derived_type_key key{kind,child,payload};if(auto i=added_derived_type_index_.find(key);i!=added_derived_type_index_.end()){out=i->second;return{};}if(auto i=owner_->derived_type_index_.find(key);i!=owner_->derived_type_index_.end()){out=i->second;return{};}try{const auto raw=owner_->canonical_types_.size()+added_canonical_types_.size();if(raw>std::numeric_limits<std::uint32_t>::max())return failure_={status_code::initialization_failed};out=TypeRef{static_cast<std::uint32_t>(raw)};graph::canonical_type_record r;r.kind=canonical_type_kind::derived;r.derived={kind,child,payload};added_canonical_types_.push_back(r);added_derived_type_index_.emplace(key,out);return{};}catch(...){return failure_={status_code::initialization_failed};}}

status graph_update::build_contribution(const enum_build_data& d,graph::source_contribution& out)noexcept
{ out.kind=entity_kind::enum_type;if(d.definition_state==enum_definition_state::opaque&&!d.enumerators.empty())return{status_code::configuration_failed}; builtin_type u=builtin_type::integer;const auto& abi=owner_->abi_;if(d.explicit_underlying){if(!is_integral(*d.explicit_underlying))return{status_code::configuration_failed};u=*d.explicit_underlying;}else if(d.scoped)u=builtin_type::integer;else{if(d.definition_state==enum_definition_state::opaque)return{status_code::configuration_failed};auto s=select_unscoped_enum_underlying_projected(d.enumerators,abi,u,[](const enum_value_build& value)noexcept{return value.value;});if(!s.ok())return s;}
 try{std::shared_ptr<graph::definition_payload> p;if(d.definition_state==enum_definition_state::defined){p=std::make_shared<graph::definition_payload>();p->underlying=u;p->values.reserve(d.enumerators.size());for(const auto& x:d.enumerators){auto w=builtin_bit_width(x.value.type,abi);if(!x.name||!w||(x.value.bits&~mask(w))||!fits(x.value,u,abi))return{status_code::configuration_failed};p->values.push_back({x.name,convert(x.value,u,abi)});}}out.state=d.definition_state;out.scoped=d.scoped;out.fixed=d.explicit_underlying.has_value()||d.scoped;out.underlying=u;out.definition=std::move(p);return{};}catch(...){return{status_code::initialization_failed};}}

status graph_update::add_delta(source_id source,stable_id id,const graph::source_contribution& c)noexcept
{try{auto& a=touch_entity(id.value()).aggregate;if(c.kind==entity_kind::aggregate_type){if(a.declarations)return{status_code::configuration_failed};if(c.state==enum_definition_state::defined){if(a.aggregate_definitions)return{status_code::configuration_failed};a.aggregate_definitions=1;a.aggregate_definition_source=source;}else ++a.aggregate_declarations;return{};}if(a.aggregate_declarations||a.aggregate_definitions)return{status_code::configuration_failed};if(a.declarations&&((c.scoped&&a.unscoped)||(!c.scoped&&a.scoped)||(c.fixed&&a.nonfixed)||(!c.fixed&&a.fixed)))return{status_code::configuration_failed};auto ix=static_cast<std::size_t>(c.underlying);if(c.fixed&&a.active_fixed&&a.underlying[ix]==0)return{status_code::configuration_failed};if(c.state==enum_definition_state::defined&&a.definitions)return{status_code::configuration_failed};++a.declarations;++(c.scoped?a.scoped:a.unscoped);++(c.fixed?a.fixed:a.nonfixed);if(c.fixed&&a.underlying[ix]++==0){++a.active_fixed;a.active_type=c.underlying;}if(c.state==enum_definition_state::defined){a.definitions=1;a.definition_source=source;a.definition=c.definition;}return{};}catch(...){return{status_code::initialization_failed};}}

status graph_update::remove_delta(source_id source,const graph::source_contribution& c)noexcept
{try{auto& s=touch_entity(c.entity.value());auto& a=s.aggregate;if(c.kind==entity_kind::aggregate_type){if(c.state==enum_definition_state::defined){assert(a.aggregate_definition_source==source);a.aggregate_definitions=0;a.aggregate_definition_source={};}else --a.aggregate_declarations;return materialize(c.entity,s.entity.record.name);}--a.declarations;--(c.scoped?a.scoped:a.unscoped);--(c.fixed?a.fixed:a.nonfixed);if(c.fixed){auto& n=a.underlying[static_cast<std::size_t>(c.underlying)];if(--n==0)--a.active_fixed;}if(c.state==enum_definition_state::defined){assert(a.definition_source==source);a.definitions=0;a.definition.reset();a.definition_source={};}return materialize(c.entity,s.entity.record.name);}catch(...){return{status_code::initialization_failed};}}

status graph_update::assign_type(stable_id,graph::entity_slot& e,std::unique_ptr<graph::type_storage> p)noexcept
{try{std::uint32_t h=e.record.type.value();if(!h){if(claimed_free_type_slots_.size()<owner_->free_type_slots_.size()){h=owner_->free_type_slots_[owner_->free_type_slots_.size()-1-claimed_free_type_slots_.size()];claimed_free_type_slots_.push_back(h);}else h=next_type_slot_++;e.record.type=type_handle{h};}auto& t=touch_type(h);t.kind=candidate_type_kind::replacement;t.value=std::move(p);TypeRef ignored;return get_or_create_named_type_ref(e.record.type,ignored);}catch(...){return{status_code::initialization_failed};}}

status graph_update::materialize(stable_id id,string_id name)noexcept
{try{auto& s=touch_entity(id.value());auto& a=s.aggregate;if(!a.declarations&&!a.aggregate_declarations&&!a.aggregate_definitions){if(s.entity.live){touch_identity(s.entity.record.name.value()).value={};if(s.entity.record.type){auto& t=touch_type(s.entity.record.type.value());t.kind=candidate_type_kind::removed;t.value.reset();}}s.entity.live=false;return{};}auto p=std::make_unique<graph::type_storage>();s.entity.live=true;s.entity.record.id=id;s.entity.record.name=name;touch_identity(name.value()).value=id;if(a.aggregate_declarations||a.aggregate_definitions){const bool defined=a.aggregate_definitions!=0;p->record.kind=user_type_kind::aggregate;p->record.aggregate.definition_state=defined?aggregate_definition_state::defined:aggregate_definition_state::declared;if(s.entity.record.type&&s.entity.record.type.value()<owner_->candidate_types_.size()){auto& old=owner_->candidate_types_[s.entity.record.type.value()];if(old.generation==candidate_generation_&&old.kind==candidate_type_kind::replacement&&old.value&&old.value->record.kind==user_type_kind::aggregate)p->members=std::move(old.value->members);}s.entity.record.kind=entity_kind::aggregate_type;s.entity.record.defining_source=defined?a.aggregate_definition_source:source_id{};return assign_type(id,s.entity,std::move(p));}const bool defined=a.definitions!=0;const auto u=defined?a.definition->underlying:a.active_type;p->record={user_type_kind::enumeration,{defined?enum_definition_state::defined:enum_definition_state::opaque,a.scoped!=0,a.fixed!=0,u,defined?static_cast<std::uint32_t>(a.definition->values.size()):0}};if(defined)p->enumerators=a.definition->values;s.entity.record.kind=entity_kind::enum_type;s.entity.record.defining_source=defined?a.definition_source:source_id{};return assign_type(id,s.entity,std::move(p));}catch(...){return{status_code::initialization_failed};}}

status graph_update::begin_source_replacement(source_id source)noexcept
{if(!failure_.ok())return failure_;if(!owner_||prepared_||committed_||!source)return failure_={status_code::invalid_state};try{if(source.value()<owner_->candidate_sources_.size()&&owner_->candidate_sources_[source.value()].generation==candidate_generation_)return{};touch_source(source.value());if(source.value()<owner_->source_states_.size()){for(const auto& c:owner_->source_states_[source.value()].named){auto r=remove_delta(source,c);if(!r.ok())return failure_=r;}for(auto h:owner_->source_states_[source.value()].anonymous_types){auto& t=touch_type(h);t.kind=candidate_type_kind::removed;t.value.reset();}}return{};}catch(...){return failure_={status_code::initialization_failed};}}

status graph_update::declare_named_enum(string_id name,source_id source,const enum_build_data& d,stable_id& entity,type_handle& type)noexcept
{entity={};type={};if(!failure_.ok())return failure_;if(!owner_||prepared_||committed_||!name||!source)return{status_code::invalid_state};try{auto r=begin_source_replacement(source);if(!r.ok())return failure_=r;auto& identity=touch_identity(name.value());auto id=identity.value;if(!id&&name.value()<owner_->identity_.size())id=owner_->identity_[name.value()];if(!id){if(!next_stable_id_)return failure_={status_code::initialization_failed};id=stable_id{next_stable_id_++};identity.value=id;}graph::source_contribution c;c.entity=id;c.name=name;r=build_contribution(d,c);if(!r.ok())return failure_=r;r=add_delta(source,id,c);if(!r.ok())return failure_=r;touch_source(source.value()).value.named.push_back(c);r=materialize(id,name);if(!r.ok())return failure_=r;entity=id;type=touch_entity(id.value()).entity.record.type;return{};}catch(...){return failure_={status_code::initialization_failed};}}

status graph_update::declare_named_type(string_id name,source_id source,aggregate_definition_state state,stable_id& entity,type_handle& type)noexcept
{entity={};type={};if(!failure_.ok())return failure_;if(!owner_||prepared_||committed_||!name||!source)return{status_code::invalid_state};try{auto r=begin_source_replacement(source);if(!r.ok())return failure_=r;auto& identity=touch_identity(name.value());auto id=identity.value;if(!id&&name.value()<owner_->identity_.size())id=owner_->identity_[name.value()];if(!id){if(!next_stable_id_)return failure_={status_code::initialization_failed};id=stable_id{next_stable_id_++};identity.value=id;}graph::source_contribution c;c.entity=id;c.name=name;c.kind=entity_kind::aggregate_type;c.state=state==aggregate_definition_state::defined?enum_definition_state::defined:enum_definition_state::opaque;r=add_delta(source,id,c);if(!r.ok())return failure_=r;touch_source(source.value()).value.named.push_back(c);r=materialize(id,name);if(!r.ok())return failure_=r;entity=id;type=touch_entity(id.value()).entity.record.type;return{};}catch(...){return failure_={status_code::initialization_failed};}}

status graph_update::add_anonymous_enum(source_id source,const enum_build_data& d,type_handle& type)noexcept
{type={};if(!failure_.ok())return failure_;if(!owner_||prepared_||committed_||!source)return{status_code::invalid_state};try{auto r=begin_source_replacement(source);if(!r.ok())return failure_=r;graph::source_contribution c;r=build_contribution(d,c);if(!r.ok()||d.definition_state!=enum_definition_state::defined)return failure_=r.ok()?status{status_code::configuration_failed}:r;auto p=std::make_unique<graph::type_storage>();p->anonymous=true;p->anonymous_source=source;p->record={user_type_kind::enumeration,{enum_definition_state::defined,d.scoped,c.fixed,c.underlying,static_cast<std::uint32_t>(c.definition->values.size())}};p->enumerators=c.definition->values;std::uint32_t h;if(claimed_free_type_slots_.size()<owner_->free_type_slots_.size()){h=owner_->free_type_slots_[owner_->free_type_slots_.size()-1-claimed_free_type_slots_.size()];claimed_free_type_slots_.push_back(h);}else h=next_type_slot_++;auto& ts=touch_type(h);ts.kind=candidate_type_kind::replacement;ts.value=std::move(p);touch_source(source.value()).value.anonymous_types.push_back(h);type=type_handle{h};return{};}catch(...){return failure_={status_code::initialization_failed};}}

const entity_record* graph_update::find(stable_id id)const noexcept{if(!id||!owner_||prepared_||committed_)return nullptr;if(id.value()<owner_->candidate_entities_.size()){const auto& s=owner_->candidate_entities_[id.value()];if(s.generation==candidate_generation_)return s.entity.live?&s.entity.record:nullptr;}return owner_->find(id);}
const entity_record* graph_update::find(string_id n)const noexcept{if(!n||!owner_||prepared_||committed_)return nullptr;stable_id id;if(n.value()<owner_->candidate_identities_.size()&&owner_->candidate_identities_[n.value()].generation==candidate_generation_)id=owner_->candidate_identities_[n.value()].value;else if(n.value()<owner_->identity_.size())id=owner_->identity_[n.value()];return find(id);}
const user_type_record* graph_update::find(type_handle h)const noexcept{if(!h||!owner_||prepared_||committed_)return nullptr;if(h.value()<owner_->candidate_types_.size()){const auto& s=owner_->candidate_types_[h.value()];if(s.generation==candidate_generation_){if(s.kind==candidate_type_kind::removed)return nullptr;if(s.kind==candidate_type_kind::replacement)return&s.value->record;}}return owner_->find(h);}
std::span<const enum_value_record> graph_update::enum_values(type_handle h)const noexcept{if(!h||!owner_||prepared_||committed_)return{};if(h.value()<owner_->candidate_types_.size()){const auto& s=owner_->candidate_types_[h.value()];if(s.generation==candidate_generation_){if(s.kind==candidate_type_kind::removed)return{};if(s.kind==candidate_type_kind::replacement)return s.value->enumerators;}}return owner_->enum_values(h);}

status graph_update::remove_named_entity_for_testing(stable_id id)noexcept{if(!id||!find(id))return{status_code::invalid_state};try{for(auto source:changed_sources_){auto& v=touch_source(source).value.named;for(auto i=v.begin();i!=v.end();)if(i->entity==id){auto c=*i;i=v.erase(i);auto r=remove_delta(source_id{source},c);if(!r.ok())return failure_=r;}else++i;}return{};}catch(...){return failure_={status_code::initialization_failed};}}

status graph_update::prepare_publish(const source_manager_update& sources,const string_registry_update& strings)noexcept
{if(!failure_.ok())return failure_;if(!owner_||prepared_||committed_||owner_->generation_!=base_generation_)return failure_={status_code::invalid_state};for(auto s:changed_sources_){if(!sources.contains_for_validation(source_id{s}))return failure_={status_code::configuration_failed};for(const auto& c:owner_->candidate_sources_[s].value.named){if(!strings.get_for_validation(c.name))return failure_={status_code::configuration_failed};if(c.definition)for(const auto& v:c.definition->values)if(!strings.get_for_validation(v.name))return failure_={status_code::configuration_failed};}}std::size_t added_member_count=0;for(auto h:changed_types_){const auto&c=owner_->candidate_types_[h];if(c.kind==candidate_type_kind::replacement&&c.value){added_member_count+=c.value->members.size();for(const auto&m:c.value->members)if(!strings.get_for_validation(m.name)||!m.type)return failure_={status_code::configuration_failed};}}try{if(owner_->identity_.size()<owner_->candidate_identities_.size())owner_->identity_.resize(owner_->candidate_identities_.size());if(owner_->entities_.size()<owner_->candidate_entities_.size())owner_->entities_.resize(owner_->candidate_entities_.size());if(owner_->enum_aggregates_.size()<owner_->candidate_entities_.size())owner_->enum_aggregates_.resize(owner_->candidate_entities_.size());if(owner_->source_states_.size()<owner_->candidate_sources_.size())owner_->source_states_.resize(owner_->candidate_sources_.size());const auto needed=next_type_slot_-1;if(owner_->types_.size()<needed)owner_->types_.resize(needed);owner_->free_type_slots_.reserve(owner_->free_type_slots_.size()+changed_types_.size());owner_->members_.reserve(owner_->members_.size()+added_member_count);owner_->canonical_types_.reserve(owner_->canonical_types_.size()+added_canonical_types_.size());std::uint32_t max_named=0;for(const auto&x:added_named_type_refs_)max_named=std::max(max_named,x.first);if(!added_named_type_refs_.empty()&&owner_->named_type_refs_.size()<=max_named)owner_->named_type_refs_.resize(static_cast<std::size_t>(max_named)+1);owner_->derived_type_index_.reserve(owner_->derived_type_index_.size()+added_derived_type_index_.size());}catch(...){return failure_={status_code::initialization_failed};}prepared_=true;return{};}

void graph_update::publish_prepared()noexcept
{assert(prepared_&&!committed_&&owner_);for(std::size_t i=0;i<claimed_free_type_slots_.size();++i)owner_->free_type_slots_.pop_back();for(auto n:changed_identities_)owner_->identity_[n]=owner_->candidate_identities_[n].value;for(auto id:changed_entities_){auto& c=owner_->candidate_entities_[id];auto& e=owner_->entities_[id];if(e.live!=c.entity.live){if(c.entity.live)++owner_->entity_count_;else --owner_->entity_count_;}e=c.entity;owner_->enum_aggregates_[id]=c.aggregate;}for(auto h:changed_types_){auto& c=owner_->candidate_types_[h];const bool was_live=owner_->types_[h-1]!=nullptr;const bool will_live=c.kind==candidate_type_kind::replacement||(c.kind==candidate_type_kind::unchanged&&was_live);if(was_live!=will_live){if(will_live)++owner_->user_type_count_;else --owner_->user_type_count_;}if(c.kind==candidate_type_kind::replacement){if(c.value->record.kind==user_type_kind::aggregate){c.value->member_begin=static_cast<std::uint32_t>(owner_->members_.size());c.value->member_count=static_cast<std::uint32_t>(c.value->members.size());owner_->members_.insert(owner_->members_.end(),std::make_move_iterator(c.value->members.begin()),std::make_move_iterator(c.value->members.end()));c.value->members.clear();}owner_->types_[h-1].swap(c.value);}else if(c.kind==candidate_type_kind::removed){owner_->types_[h-1].reset();owner_->free_type_slots_.push_back(h);}}for(auto s:changed_sources_)std::swap(owner_->source_states_[s],owner_->candidate_sources_[s].value);owner_->canonical_types_.insert(owner_->canonical_types_.end(),added_canonical_types_.begin(),added_canonical_types_.end());for(const auto&x:added_named_type_refs_)owner_->named_type_refs_[x.first]=x.second;owner_->derived_type_index_.merge(added_derived_type_index_);owner_->next_stable_id_=next_stable_id_;++owner_->generation_;committed_=true;}
void graph_update::cancel()noexcept{if(!committed_){prepared_=true;failure_={status_code::invalid_state};}}
} // namespace cw::server
